# ***Імпортуємо необхідні бібліотеки для роботи***

In [1]:
import numpy as np
import random
import time
import unittest

# ***Реалізуємо метод множення двох матриць (N x M)***

In [2]:
mA = np.random.rand(4, 4)
mB = np.random.rand(4, 4)
matrixC = np.random.rand(4, 4)
v1 = np.random.rand(4)
v2 = np.random.rand(4)
def gCAL(mTM, col):
    mL = []
    nOR = len(mTM)
    for i in range(nOR):
        mL.append(mTM[i][col])
    return mL
 
def gC(mA, mB, r, c):
    mBC = gCAL(mB, c)
    lOL = len(mBC)
    pL = [mA[r][i]*mBC[i] for i in range(lOL)]
    return sum(pL)
rowA = len(mA)
colA = len(mA[0])
rowB = len(mB)
colB = len(mB[0])
rowC = len(matrixC)
start_time1 = time.time() 
result = [[0 for p in range(colB)] for q in range(rowA)]

In [3]:
print('Multiplying matrices without NumPy: ')
for i in range(rowA):
  for j in range(colB):
        result[i][j] = gC(mA, mB, i, j)
  print(result[i])
print("--- %s seconds ---" % (time.time() - start_time1))
start_time2 = time.time()
c = np.matmul(mA, mB)
print('--------------------')
print('Multiplying matrices with NumPy')
print(c)
print("--- %s seconds ---" % (time.time() - start_time2))

Multiplying matrices without NumPy: 
[1.9763970379934286, 0.7634585025988004, 1.053082863273499, 1.4762904041659919]
[1.2095803943131396, 0.49880062507636874, 0.6721767507667729, 1.0334911669753672]
[0.8280745159319942, 0.2936414696589369, 0.5152129339349665, 0.5065427495351547]
[1.6699838044440032, 0.6866499193775223, 0.9116099360976246, 1.2792202984609156]
--- 0.017005205154418945 seconds ---
--------------------
Multiplying matrices with NumPy
[[1.97639704 0.7634585  1.05308286 1.4762904 ]
 [1.20958039 0.49880063 0.67217675 1.03349117]
 [0.82807452 0.29364147 0.51521293 0.50654275]
 [1.6699838  0.68664992 0.91160994 1.2792203 ]]
--- 0.018992185592651367 seconds ---


# ***Реалізуємо метод множення матриці (N x M) на вектор (N)***

In [4]:
start_time3 = time.time()
N = 2
t = [0]*(N)
for i in range(N):
  t[i]=0
for i in range(N):
  for j in range(N):
    t[i] += (mA[i][j] * v1[j])

In [5]:
print('Matrix multiplied by a vector without NumPy')
print(t)
print("--- %s seconds ---" % (time.time() - start_time3))
print('------------')
print('Matrix multiplied by a vector with NumPy')
start_time4 = time.time()
total = np.matmul(mA, v1)
print(total)
print("--- %s seconds ---" % (time.time() - start_time4))

Matrix multiplied by a vector without NumPy
[0.5113424525734949, 0.38800723256446756]
--- 0.019001007080078125 seconds ---
------------
Matrix multiplied by a vector with NumPy
[0.63729536 0.46212137 0.27242766 0.56071732]
--- 0.0010020732879638672 seconds ---


# ***Реалізуємо метод множення вектора (N) на матрицю (N x M)***

In [6]:
start_time5 = time.time()
N = 4
b = [0]*(N)
for i in range(N):
  b[i]=0

for i in range(N):
  for j in range(N):
    b[i] += (v2[j] * mB[j][i])

In [7]:
print('Multiplying a Vector by a Matrix  without NumPy')
print(b)
print("--- %s seconds ---" % (time.time() - start_time5))
print('--------')
print('Multiplying a Vector by a Matrix with NumPy')
start_time6 = time.time()
help = v2.dot(mB)
print(help)
print("--- %s seconds ---" % (time.time() - start_time6))

Multiplying a Vector by a Matrix  without NumPy
[1.0682164084034143, 0.23392102492269662, 0.4911010008942399, 0.3633802612718113]
--- 0.02199864387512207 seconds ---
--------
Multiplying a Vector by a Matrix with NumPy
[1.06821641 0.23392102 0.491101   0.36338026]
--- 0.001003265380859375 seconds ---


# ***Реалізуємо метод множення двох векторів (N)***

In [8]:
start_time7 = time.time()
def vectorOnVector(v1, v2):
    lenght = len(v1)
    scalar = 0
    for i in range(lenght):
        scalar = scalar + v1[i]*v2[i]
    return scalar

In [9]:
scalar = vectorOnVector(v1, v2)
print('Multiplication of two vectors without NumPy')
print(scalar)
print("--- %s seconds ---" % (time.time() - start_time7))
print('--------')
print('Multiplication of two vectors with NumPy')
start_time8 = time.time()
well = v1.dot(v2)
print(well)
print("--- %s seconds ---" % (time.time() - start_time8))

Multiplication of two vectors without NumPy
0.12602058189866072
--- 0.01000070571899414 seconds ---
--------
Multiplication of two vectors with NumPy
0.12602058189866075
--- 0.0 seconds ---
